//! Bakes node binaries into the control plane so it can serve updates.
//!
//! Scans a directory laid out as `<target triple>/<binary>` and generates a table of everything
//! it finds, with each file's bytes included via `include_bytes!` and its SHA-256 computed here
//! rather than at runtime. Hashing at build time means the control plane can answer a manifest
//! request without touching the payload, and means a corrupted embed is a build failure rather
//! than something a node discovers.
//!
//! Nothing staged is not an error. A control plane built without artifacts simply offers no
//! updates, which is exactly right for a development build and for the bootstrap case where the
//! binaries cannot exist yet because they are built from this same tree.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use sha2::{Digest, Sha256};

/// Binaries worth serving. Anything else in the directory is ignored, so a target folder can
/// hold whatever else a release process leaves lying about.
const WANTED: [&str; 2] = ["meshd", "meshctl"];

fn main() {
    println!("cargo:rerun-if-env-changed=MESH_EMBED_DIR");

    let root = std::env::var("MESH_EMBED_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| {
            // Default to `dist/` at the workspace root, which is where CI stages the matrix's
            // artifacts before building this crate.
            Path::new(env!("CARGO_MANIFEST_DIR"))
                .parent()
                .and_then(|p| p.parent())
                .unwrap_or(Path::new("."))
                .join("dist")
        });
    println!("cargo:rerun-if-changed={}", root.display());

    let mut entries = String::new();
    let mut count = 0usize;

    if let Ok(targets) = std::fs::read_dir(&root) {
        let mut targets: Vec<_> = targets.filter_map(|e| e.ok()).collect();
        // Sorted so the generated file is identical run to run, which keeps rebuilds cheap.
        targets.sort_by_key(|e| e.file_name());
        for target in targets {
            if !target.path().is_dir() {
                continue;
            }
            let triple = target.file_name().to_string_lossy().into_owned();
            for name in WANTED {
                for candidate in [name.to_string(), format!("{name}.exe")] {
                    let path = target.path().join(&candidate);
                    let Ok(bytes) = std::fs::read(&path) else {
                        continue;
                    };
                    println!("cargo:rerun-if-changed={}", path.display());
                    let digest = hex(&Sha256::digest(&bytes));
                    writeln!(
                        entries,
                        "    Embedded {{ target: {:?}, name: {:?}, sha256: {:?}, bytes: include_bytes!({:?}) }},",
                        triple,
                        name,
                        digest,
                        path.to_string_lossy()
                    )
                    .expect("writing to a String cannot fail");
                    count += 1;
                    break; // one file per logical binary, extension or not
                }
            }
        }
    }

    let generated = format!(
        "// Generated by build.rs. Do not edit.\n\
         pub struct Embedded {{\n\
         \x20   pub target: &'static str,\n\
         \x20   pub name: &'static str,\n\
         \x20   pub sha256: &'static str,\n\
         \x20   pub bytes: &'static [u8],\n\
         }}\n\n\
         pub static EMBEDDED: &[Embedded] = &[\n{entries}];\n"
    );
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets OUT_DIR"))
        .join("embedded_binaries.rs");
    std::fs::write(&out, generated).expect("writing the generated table");

    // Only worth a word when there is something to say. A development build with nothing staged
    // is the normal case, and a warning on every compile would train people to ignore them; the
    // daemon already reports at startup that it offers no updates.
    if count > 0 {
        println!(
            "cargo:warning=meshcp embedded {count} node binaries from {}",
            root.display()
        );
    }
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().fold(String::new(), |mut s, b| {
        let _ = write!(s, "{b:02x}");
        s
    })
}
